### ISSUE TITLE
Error when Background section has a Given clause

### ISSUE THREAD

**Issue by asiermarques** [raviqqe/gherkin2markdown#1] opened 2019-05-01 14:35 UTC
If the Background section in a feature file has a Given clause it can't parse the file. For example:
```gherkin
  Background:

  We want to edit a talk proposal in our application.

  Given the following proposals were sent to the system:

    | identifier | title    | speakers                    | visible | votes |
    | 1          | A title  | Ana Smith and Tobias Walter | false   | 0     |
```

The command throws the  exception with:

```
panic: unreachable

goroutine 1 [running]:
main.renderer.renderStep(0xc0000e1e58, 0xc00011c680, 0x1)
	/go/src/github.com/raviqqe/gherkin2markdown/renderer.go:86 +0x4b6
main.renderer.renderSteps(0xc0000e1e58, 0xc000096068, 0x1, 0x1)
	/go/src/github.com/raviqqe/gherkin2markdown/renderer.go:62 +0x62
main.renderer.renderBackground(0xc0000e1e58, 0xc0001200a0)
	/go/src/github.com/raviqqe/gherkin2markdown/renderer.go:45 +0x1ac
main.renderer.renderFeature(0xc0000e1e58, 0xc0000fa300)
	/go/src/github.com/raviqqe/gherkin2markdown/renderer.go:33 +0x2f6
main.renderer.Render(...)
	/go/src/github.com/raviqqe/gherkin2markdown/renderer.go:19
main.convertFile(0x7ffeefbffbf4, 0x3a, 0x136d120, 0xc00009a000, 0x1, 0x12a66e0)
	/go/src/github.com/raviqqe/gherkin2markdown/convert.go:29 +0xf2
main.command(0xc00009e010, 0x1, 0x1, 0x136d120, 0xc00009a000, 0x0, 0x0)
	/go/src/github.com/raviqqe/gherkin2markdown/main.go:26 +0x18c
main.main()
	/go/src/github.com/raviqqe/gherkin2markdown/main.go:10 +0x82
```

**Comment by raviqqe** [comment] 2019-05-01 15:50
It was missing data table rendering. It should be fixed on master. Could you check that?

**Comment by asiermarques** [comment] 2019-05-01 17:12
It works!! The only problem now is that the table is not properly formatted.

```
_Given_ the following proposals were sent to the system:

| identifier | title   | speakers                    | visible | votes |
| 1          | A title | Ana Smith and Tobias Walter | false   | 0     |
```

instead of

```
_Given_ the following proposals were sent to the system:

| identifier | title   | speakers                    | visible | votes |
|------------|---------|-----------------------------|---------|-------|
| 1          | A title | Ana Smith and Tobias Walter | false   | 2     |
```

But it does the job, thank you!

**Comment by raviqqe** [comment] 2019-05-02 04:29
Different from tables for examples, [data tables do not seem to have headers](https://github.com/cucumber/cucumber-messages-go/blob/master/v2/messages.pb.go#L2030). Closing as the issue is fixed. Thanks for your contribution!

**Closed by raviqqe** 2019-05-02 04:29 UTC
